// ============================================================
// KONTEN TERJEMAHAN — Angka Akar (Life Path) & Elemen Wu Xing
// Bahasa: Indonesia (id), English (en), Mandarin Simplified (zh)
// Sumber: materi resmi Wuterra, diterjemahkan menjaga makna aslinya.
// ============================================================

export const LIFE_PATH_CONTENT = {
  id: {
    1: { title: "Sang Pemikir Bijaksana", desc: "Anda adalah pemikir yang bijaksana dengan kemampuan analisa yang kuat — jika diarahkan dengan baik, sifat ini bisa menjadikan Anda orang yang terpelajar. Jawaban Anda penuh pertimbangan, mendetail, dan penuh kreativitas, dilengkapi selera humor yang membuat Anda mudah menjalin relasi. Jiwa kepemimpinan dan karisma Anda justru semakin kuat seiring bertambahnya usia.", traits: ["Analitis", "Bijaksana", "Karismatik"], highlight: "Puncak peluang kesuksesan finansial ada di rentang usia 32-42 tahun" },
    2: { title: "Sang Penghubung yang Empatik", desc: "Anda supel dan pandai bicara, mampu membangun relasi baik dengan siapa pun berkat sikap yang ramah. Empati Anda tinggi dan sensitif terhadap perasaan orang lain, sekaligus terorganisir dan pekerja keras — menyukai kerapian dan selalu mempertimbangkan hasil akhir sebelum memulai sesuatu.", traits: ["Empatik", "Supel", "Terorganisir"], highlight: "Berhati lembut dan banyak bicara — mendapat dukungan dari lawan jenis" },
    3: { title: "Sang Pengejar Peluang", desc: "Anda atraktif sejak usia muda, agresif, dan berorientasi ke masa depan — mampu membaca peluang bahkan di tengah situasi yang sulit dan mengambil keputusan dengan cepat. Jiwa kepemimpinan ini bisa membawa Anda pada kehidupan yang mapan sebelum usia 30 tahun. Di balik semangat itu, waspadai kecenderungan tidak sabar dan cepat marah, meski sisi spiritual Anda cukup kuat.", traits: ["Agresif", "Cepat bertindak", "Spiritual"], highlight: "Berpeluang hidup mapan sebelum usia 30 tahun" },
    4: { title: "Sang Perencana Cerdas", desc: "Anda cerdas, artistik, dan unggul dalam bidang akademis — layak dipercaya dan mudah bergaul di masyarakat. Sebagai perencana dan pemikir alami, Anda selalu berpikir dahulu sebelum bertindak dalam mengambil keputusan. Bakat Anda terlihat sejak usia muda, termasuk cita rasa tinggi dalam kuliner yang berpotensi menjadikan Anda seorang chef handal.", traits: ["Cerdas", "Artistik", "Perencana"], highlight: "Cocok berkarier di bidang akademik, seni, atau kuliner" },
    5: { title: "Sang Pejuang Tangguh", desc: "Anda terlahir dengan karakter yang kuat dan jiwa kepemimpinan yang karismatik. Realistis dan pekerja keras, Anda mampu menyesuaikan diri dengan situasi sulit serta menghadapi rintangan dengan daya juang tinggi. Tantangan terbesar Anda adalah belajar lebih menghargai pendapat orang lain di sekitar Anda.", traits: ["Tangguh", "Realistis", "Pekerja keras"], highlight: "Kekuatan terbesar ada pada daya juang menghadapi rintangan" },
    6: { title: "Sang Pengelola Kesejahteraan", desc: "Anda cakap dalam mengontrol kekayaan dan kesejahteraan, sopan, dan memiliki selera tinggi dalam menjalani hidup. Karier Anda akan bersinar di bidang seni, keagamaan, atau pendidikan, dan Anda punya potensi menjadi figur yang populer. Keluarga adalah prioritas utama Anda — namun waspadai kecenderungan posesif dalam hubungan dekat.", traits: ["Pengelola andal", "Berorientasi keluarga", "Populer"], highlight: "Keberuntungan besar cenderung datang sekitar usia 45 tahun" },
    7: { title: "Sang Pencari Makna", desc: "Anda sangat detail dan tahu balas budi, dengan semangat mengejar ketenaran dan keberuntungan. Di usia matang, Anda berpotensi menjadi figur atau pemimpin religius yang dihormati. Keberuntungan Anda didukung oleh perhatian dan dukungan dari lawan jenis.", traits: ["Detail", "Setia", "Reflektif"], highlight: "Potensi menjadi figur atau pemimpin religius di atas usia 50 tahun" },
    8: { title: "Sang Penjaga Komitmen", desc: "Anda pendiam dan konservatif, namun sangat bertanggung jawab dalam memegang komitmen. Meski terlihat tegas dan keras di luar, hati Anda sebenarnya lembut. Kesibukan dan sisi emosional membuat Anda rentan stres di bawah tekanan, tapi rasa tanggung jawab Anda tetap menjadi kekuatan utama.", traits: ["Bertanggung jawab", "Tegas", "Berhati lembut"], highlight: "Kekuatan utama: memegang komitmen meski di bawah tekanan" },
    9: { title: "Sang Visioner Optimis", desc: "Anda optimis, berpikiran terbuka, dan senang tampil elegan. Pribadi yang bersahaja dan sensitif ini pandai mengambil simpati orang lain, serta bekerja keras untuk mengejar impian besar. Keberuntungan dan kesuksesan cenderung datang di atas usia 35 tahun — tetap waspadai kecenderungan serakah saat mengejar ambisi.", traits: ["Optimis", "Inovatif", "Berimpian besar"], highlight: "Keberuntungan & kesuksesan besar cenderung muncul di atas usia 35 tahun" },
  },
  en: {
    1: { title: "The Wise Thinker", desc: "You are a wise thinker with strong analytical skills — when channeled well, this trait can make you a truly learned person. Your answers are thoughtful, detailed, and creative, backed by a sense of humor that makes it easy for you to build relationships. Your leadership and charisma only grow stronger with age.", traits: ["Analytical", "Wise", "Charismatic"], highlight: "Your biggest window for financial success falls between ages 32-42" },
    2: { title: "The Empathetic Connector", desc: "You're sociable and articulate, able to build good relationships with almost anyone thanks to your warm nature. Highly empathetic and sensitive to others' feelings, you're also organized and hardworking — you value tidiness and always think through the end result before starting anything.", traits: ["Empathetic", "Sociable", "Organized"], highlight: "Soft-hearted and talkative — you tend to draw support from the opposite sex" },
    3: { title: "The Opportunity Seeker", desc: "You're attractive from a young age, driven, and future-oriented — able to spot opportunity even in difficult situations and make quick decisions. This leadership spirit can bring you a settled, comfortable life before age 30. Behind that drive, watch out for impatience and a quick temper, even as your spiritual side stays strong.", traits: ["Driven", "Quick to act", "Spiritual"], highlight: "You have real potential to be financially settled before age 30" },
    4: { title: "The Smart Planner", desc: "You're intelligent, artistic, and excel academically — trustworthy and easy to get along with in society. As a natural planner and thinker, you always think before you act when making decisions. Your talent shows early in life, including a refined palate that could make you an excellent chef.", traits: ["Intelligent", "Artistic", "Planner"], highlight: "Well-suited to careers in academia, the arts, or culinary fields" },
    5: { title: "The Resilient Fighter", desc: "You were born with a strong character and charismatic leadership instincts. Realistic and hardworking, you adapt well to difficult situations and face obstacles with real fighting spirit. Your biggest growth area is learning to value other people's opinions more.", traits: ["Resilient", "Realistic", "Hardworking"], highlight: "Your greatest strength lies in your fighting spirit against obstacles" },
    6: { title: "The Prosperity Manager", desc: "You're skilled at managing wealth and wellbeing, courteous, and hold refined taste in how you live. Your career will shine in the arts, religion, or education, and you have real potential to become a popular public figure. Family is your top priority — but watch for a tendency toward possessiveness in close relationships.", traits: ["Reliable manager", "Family-oriented", "Popular"], highlight: "Major good fortune tends to arrive around age 45" },
    7: { title: "The Meaning Seeker", desc: "You're highly detail-oriented and know how to repay kindness, driven by a spirit chasing fame and fortune. In your mature years, you have real potential to become a respected figure or religious leader. Your fortune is bolstered by attention and support from the opposite sex.", traits: ["Detail-oriented", "Loyal", "Reflective"], highlight: "Potential to become a respected figure or religious leader after age 50" },
    8: { title: "The Commitment Keeper", desc: "You're quiet and conservative, yet deeply responsible when it comes to keeping commitments. Though you may look tough and stern on the outside, your heart is genuinely soft. Busyness and emotional sensitivity can leave you prone to stress under pressure, but your sense of responsibility remains your greatest strength.", traits: ["Responsible", "Firm", "Soft-hearted"], highlight: "Your core strength: keeping commitments even under pressure" },
    9: { title: "The Optimistic Visionary", desc: "You're optimistic, open-minded, and enjoy presenting yourself with elegance. Down-to-earth yet sensitive, you're skilled at winning people's sympathy and work hard chasing big dreams. Fortune and success tend to arrive after age 35 — but stay mindful of a tendency toward greed while chasing ambition.", traits: ["Optimistic", "Innovative", "Big dreamer"], highlight: "Major fortune and success tend to emerge after age 35" },
  },
  zh: {
    1: { title: "智慧的思考者", desc: "您是一位富有智慧的思考者,拥有强大的分析能力——如果善加引导,这种特质能让您成为博学之人。您的回答总是深思熟虑、细致入微且富有创意,加上幽默感,使您很容易建立人际关系。您的领导力和魅力会随着年龄增长而愈发强大。", traits: ["善于分析", "睿智", "有魅力"], highlight: "32-42岁是您财富成功的黄金窗口期" },
    2: { title: "富有同理心的联结者", desc: "您健谈随和,凭借友善的态度能与任何人建立良好关系。您同理心强,对他人情感敏感,同时也很有条理、勤奋努力——喜欢整洁,做事前总会考虑最终结果。", traits: ["富有同理心", "随和", "有条理"], highlight: "心地柔软、健谈——容易获得异性的支持" },
    3: { title: "机遇追寻者", desc: "您从年轻时就很有魅力,积极进取,着眼未来——即使在困境中也能敏锐察觉机会并迅速做出决定。这种领导气质能让您在30岁前就拥有安稳的生活。不过也要留意急躁易怒的倾向,尽管您的灵性一面相当强大。", traits: ["积极进取", "行动迅速", "灵性强"], highlight: "很有可能在30岁前就拥有安稳的生活" },
    4: { title: "聪慧的规划者", desc: "您聪明、有艺术天赋,并在学术领域表现出色——值得信赖,也容易与人相处。作为天生的规划者和思考者,您做决定前总会三思而后行。您的才华从年轻时就已展现,包括对美食敏锐的品味,很有潜力成为出色的厨师。", traits: ["聪明", "有艺术天赋", "善规划"], highlight: "适合往学术、艺术或餐饮领域发展" },
    5: { title: "坚韧的奋斗者", desc: "您天生个性坚强,具有极具魅力的领导气质。务实且勤奋,您能很好地适应困境,并以顽强的斗志面对阻碍。您最大的课题是学习更加尊重他人的意见。", traits: ["坚韧", "务实", "勤奋"], highlight: "您最大的优势在于面对阻碍时的顽强斗志" },
    6: { title: "财富管理者", desc: "您擅长管理财富与生活品质,举止得体,生活品味不俗。您的事业将在艺术、宗教或教育领域大放异彩,也很有潜力成为受欢迎的公众人物。家庭是您最优先的重心——但要留意在亲密关系中可能出现的占有欲。", traits: ["善于管理", "以家庭为重", "受欢迎"], highlight: "重大好运通常在45岁左右到来" },
    7: { title: "意义追寻者", desc: "您非常注重细节,懂得知恩图报,心中怀有追求名望与好运的热忱。步入成熟年纪后,您很有潜力成为受人尊敬的人物或宗教领袖。异性的关注与支持也为您的好运加分。", traits: ["注重细节", "忠诚", "善于反思"], highlight: "50岁以后有潜力成为受尊敬的人物或宗教领袖" },
    8: { title: "承诺的守护者", desc: "您性格安静、保守,但在信守承诺方面极其负责任。尽管外表看起来严肃强硬,您的内心其实十分柔软。忙碌与情绪敏感容易让您在压力下感到紧张,但责任感始终是您最大的力量。", traits: ["有责任感", "坚定", "内心柔软"], highlight: "核心优势:即使在压力下也能信守承诺" },
    9: { title: "乐观的远见者", desc: "您乐观、思想开放,喜欢展现优雅的一面。您朴实而敏感,擅长赢得他人的同情,并为追逐远大梦想而努力奋斗。财富与成功往往在35岁之后到来——但在追逐野心时也要留意贪婪的倾向。", traits: ["乐观", "善于创新", "胸怀大志"], highlight: "重大好运与成功往往在35岁以后显现" },
  },
};

export const ELEMENT_CONTENT = {
  id: {
    kayu: { name: "Kayu", desc: "Kayu melambangkan pertumbuhan, fleksibilitas, dan kreativitas yang terus berkembang. Orang dengan elemen ini cenderung mudah beradaptasi namun tetap punya arah yang jelas.", colors: "hijau tua, hijau lumut", industries: "kreatif, pendidikan, lingkungan, startup" },
    api: { name: "Api", desc: "Api melambangkan semangat, kepemimpinan, dan energi yang menyala terang. Orang dengan elemen ini membawa antusiasme yang mudah menular ke sekitarnya.", colors: "merah, oranye, ungu terang", industries: "wirausaha, hiburan, penjualan, olahraga" },
    tanah: { name: "Tanah", desc: "Tanah melambangkan stabilitas, kepercayaan, dan kemampuan menopang orang lain. Orang dengan elemen ini menjadi tempat berpijak yang kokoh bagi lingkungannya.", colors: "kuning, cokelat, krem", industries: "properti, keuangan, konsultasi, agrikultur" },
    logam: { name: "Logam", desc: "Logam melambangkan ketelitian, struktur, dan prinsip yang tegas. Orang dengan elemen ini menghargai kualitas dan tidak mudah berkompromi pada standar.", colors: "putih, abu-abu, emas pucat", industries: "hukum, teknik, keuangan, manufaktur" },
    air: { name: "Air", desc: "Air melambangkan intuisi, adaptasi, dan kedalaman berpikir. Orang dengan elemen ini bergerak tenang namun mampu menembus hambatan yang paling keras sekalipun.", colors: "biru, hitam, biru dongker", industries: "riset, terapi, sastra, strategi" },
  },
  en: {
    kayu: { name: "Wood", desc: "Wood represents growth, flexibility, and ever-expanding creativity. People with this element tend to adapt easily while still keeping a clear sense of direction.", colors: "deep green, moss green", industries: "creative fields, education, environment, startups" },
    api: { name: "Fire", desc: "Fire represents passion, leadership, and blazing energy. People with this element carry an enthusiasm that's easy to catch.", colors: "red, orange, bright purple", industries: "entrepreneurship, entertainment, sales, sports" },
    tanah: { name: "Earth", desc: "Earth represents stability, trustworthiness, and the ability to support others. People with this element become a solid foundation for those around them.", colors: "yellow, brown, cream", industries: "property, finance, consulting, agriculture" },
    logam: { name: "Metal", desc: "Metal represents precision, structure, and firm principles. People with this element value quality and rarely compromise on standards.", colors: "white, grey, pale gold", industries: "law, engineering, finance, manufacturing" },
    air: { name: "Water", desc: "Water represents intuition, adaptability, and depth of thought. People with this element move calmly yet can break through even the toughest obstacles.", colors: "blue, black, navy", industries: "research, therapy, literature, strategy" },
  },
  zh: {
    kayu: { name: "木", desc: "木象征着成长、灵活与不断发展的创造力。这个属性的人通常容易适应变化,同时仍保有清晰的方向感。", colors: "深绿色、苔绿色", industries: "创意产业、教育、环保、初创企业" },
    api: { name: "火", desc: "火象征着热情、领导力与炽热的能量。这个属性的人身上散发着极具感染力的热忱。", colors: "红色、橙色、亮紫色", industries: "创业、娱乐业、销售、体育" },
    tanah: { name: "土", desc: "土象征着稳定、可信赖,以及支撑他人的能力。这个属性的人是身边人可以依靠的坚实基础。", colors: "黄色、棕色、米色", industries: "房地产、金融、咨询、农业" },
    logam: { name: "金", desc: "金象征着严谨、条理与坚定的原则。这个属性的人重视品质,不轻易在标准上妥协。", colors: "白色、灰色、淡金色", industries: "法律、工程、金融、制造业" },
    air: { name: "水", desc: "水象征着直觉、适应力与深邃的思考。这个属性的人行事沉稳,却能突破最艰难的阻碍。", colors: "蓝色、黑色、藏青色", industries: "研究、心理咨询、文学、策略规划" },
  },
};

export const SUPPORTED_LANGS = ["id", "en", "zh"];
export const DEFAULT_LANG = "id";

export function normalizeLang(lang) {
  return SUPPORTED_LANGS.includes(lang) ? lang : DEFAULT_LANG;
}
